# Build on push to main and PRs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Ccache settings inspired from here:
# https://github.com/strongswan/strongswan/blob/master/.github/workflows/tkm.yml
env:
  CCACHE_DIR: ${{ github.workspace }}/.ccache
  CCACHE_CONTAINER: /root/.ccache
  CCACHE_COMPILERCHECK: content
  CCACHE_COMPRESS: true
  CCACHE_MAXSIZE: 200M

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:release-v5.1

      # mount ccache dir from outside the container, so cache save + restore
      # works
      options: |
        --volume ${{ env.CCACHE_DIR }}:${{ env.CCACHE_CONTAINER }}
        -e CCACHE_DIR=${{ env.CCACHE_CONTAINER }}
        -e CCACHE_COMPILERCHECK
        -e CCACHE_COMPRESS
        -e CCACHE_MAXSIZE

    steps:
      # checkout and update submodules
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Cache Ccache
        id: ccache
        uses: actions/cache@v3
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-ccache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      # workaround: https://github.com/actions/runner/issues/2033#issuecomment-1204205989
      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD

      - name: Build
        run: |
          # set memfault project key from github secret
          echo "CONFIG_MEMFAULT_PROJECT_KEY=\"${{ secrets.MEMFAULT_PROJECT_KEY }}\"" >> sdkconfig.defaults
          # create a build id using calver + git short rev
          echo "CONFIG_MEMFAULT_ESP32_MAIN_FIRMWARE_VERSION=\"$(date -u +'%Y.%m.%d')+$(git rev-parse --short HEAD)\"" >> sdkconfig.defaults

          # activate esp-idf environment
          . /opt/esp/idf/export.sh

          idf.py set-target esp32s3
          idf.py build
