# Build on push to main and PRs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: espressif/idf:release-v5.1
    steps:
      - uses: actions/checkout@v3

      # workaround: https://github.com/actions/runner/issues/2033#issuecomment-1204205989
      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD

      - name: Build
        run: |
          # set memfault project key from github secret
          echo "CONFIG_MEMFAULT_PROJECT_KEY=\"${{ secrets.MEMFAULT_PROJECT_KEY }}\"" >> sdkconfig.defaults
          # create a build id using calver + git short rev
          echo "CONFIG_MEMFAULT_ESP32_MAIN_FIRMWARE_VERSION=\"$(date -u +'%Y.%m.%d')+$(git rev-parse --short HEAD)\"" >> sdkconfig.defaults

          # activate esp-idf environment
          source /opt/esp/idf/export.sh

          idf.py set-target esp32s3
          idf.py build
